const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');const fs=require('node:fs');
const {assessPull,pullLength,previewPull,samplePull}=require('../mechanics.js');
async function game({failBlack=false,reduced=false}={}){
  let time=0,id=0;const jobs=new Map(),nodes=new Map();
  const schedule=(fn,ms=0)=>{jobs.set(++id,{fn,at:time+ms});return id};
  const element=()=>{const events={},styles=new Map(),classes=new Set();return{events,dataset:{},hidden:false,value:0,textContent:'',naturalWidth:64,naturalHeight:64,
    style:{setProperty:(k,v)=>styles.set(k,v)},classList:{add:(...xs)=>xs.forEach(x=>classes.add(x)),remove:(...xs)=>xs.forEach(x=>classes.delete(x)),toggle:(x,b)=>b?classes.add(x):classes.delete(x)},
    parentElement:{setAttribute(){}},addEventListener:(k,f)=>events[k]=f,setAttribute(){},getBoundingClientRect:()=>({left:0,top:0,width:1280,height:426}),getContext:()=>({drawImage(){},clearRect(){},save(){},restore(){},beginPath(){},moveTo(){},quadraticCurveTo(){},bezierCurveTo(){},ellipse(){},fill(){},stroke(){},getImageData:()=>({data:new Uint8ClampedArray(64*64*4).fill(255)}),putImageData(){}}),setPointerCapture(){},hasPointerCapture:()=>false};};
  const get=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id)};
  const breeds=[get('yellow'),get('black')];breeds[0].dataset.breed='yellow';breeds[1].dataset.breed='black';
  const document={createElement:element,getElementById:get,querySelectorAll:selector=>selector.includes('data-breed')?breeds:[element(),element(),element()],addEventListener(){}};
  const window={matchMedia:()=>({matches:reduced}),addEventListener(){}};
  const context={window,document,matchMedia:window.matchMedia,setTimeout:schedule,performance:{now:()=>time},requestAnimationFrame:fn=>schedule(()=>fn(time),16),ResizeObserver:class{observe(){}},Image:class{constructor(){this.naturalWidth=64;this.naturalHeight=64}set src(v){this.value=v;Promise.resolve().then(()=>failBlack&&v.includes('/black/brace.')?this.onerror():this.onload())}decode(){return Promise.resolve()}}};
  for(const file of ['mechanics.js','frames.js','black-frames.js','game.js'])vm.runInNewContext(fs.readFileSync(file,'utf8'),context);
  const flush=async()=>{for(let n=0;n<100;n++)await Promise.resolve()};
  const tick=async ms=>{const end=time+ms;await flush();while(true){const next=[...jobs].filter(([,v])=>v.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;jobs.delete(next[0]);time=next[1].at;next[1].fn();await flush()}time=end;await flush()};
  const send=(type,x=600)=>get('stage').events[type]({clientX:x,clientY:250,pointerId:1,button:0,isPrimary:true,preventDefault(){},target:{id:'ropeHit'}});
  await flush();return{get,tick,send};
}

test('pull length is responsive and clamped',()=>{assert.equal(pullLength(390),93.6);assert.equal(pullLength(1280),220);assert.equal(pullLength(300),90)});
test('short, comfortable and excessive pulls yield different results',()=>{assert.equal(previewPull({tension:.07}).gain,0);assert.ok(previewPull({tension:.5}).gain>previewPull({tension:.15}).gain);assert.ok(previewPull({tension:.8}).gain<previewPull({tension:.7}).gain);assert.equal(previewPull({tension:.9}).gain,0)});
test('backoff rewards and recovery after 150ms',()=>{let p={tension:0,peak:0,sampleTime:0,valid:false};samplePull(p,1,1000);assert.equal(previewPull(p).gain,0);samplePull(p,.5,1100);samplePull(p,.5,1249);assert.equal(p.blocked,true);samplePull(p,.5,1250);assert.equal(p.blocked,false);assert.ok(previewPull(p).gain>previewPull({tension:.5}).gain)});
test('blank stage does not initiate dragging',async()=>{const g=await game();g.get('stage').events.pointerdown({button:0,target:{id:'stage'}});assert.equal(g.get('stage').dataset.state,'idle')});
test('preview changes immediately but distance commits only on release',async()=>{const g=await game();g.send('pointerdown');g.send('pointermove',490);assert.ok(+g.get('stage').dataset.preview>0);assert.equal(+g.get('stage').dataset.progress,0);const expected=+g.get('stage').dataset.preview;g.send('pointerup',490);await g.tick(16);assert.ok(Math.abs(+g.get('stage').dataset.progress-expected)<.0001);await g.tick(900);assert.equal(g.get('stage').dataset.state,'idle')});
test('cancel removes uncommitted preview',async()=>{const g=await game();g.send('pointerdown');g.send('pointermove',490);g.send('pointercancel');await g.tick(1000);assert.equal(+g.get('stage').dataset.progress,0);assert.equal(+g.get('stage').dataset.preview,0)});
test('repeat drag interrupts settling without losing distance',async()=>{const g=await game();g.send('pointerdown');g.send('pointerup',490);await g.tick(20);const before=+g.get('stage').dataset.progress;g.send('pointerdown');g.send('pointermove',510);await g.tick(1000);assert.equal(g.get('stage').dataset.state,'dragging');assert.equal(+g.get('stage').dataset.progress,before);g.send('pointerup',510);await g.tick(1000);assert.ok(+g.get('stage').dataset.progress>before)});
test('overpull is blocked, hold backoff recovers',async()=>{const g=await game();g.send('pointerdown');g.send('pointermove',370);assert.equal(+g.get('stage').dataset.preview,0);g.send('pointermove',490);await g.tick(170);assert.ok(+g.get('stage').dataset.preview>0);g.send('pointerup',490);await g.tick(1000);assert.ok(+g.get('stage').dataset.progress>0)});
test('breed switches retain progress and failure retains prior skin',async()=>{for(const failBlack of [false,true]){const g=await game({failBlack});g.send('pointerdown');g.send('pointerup',490);await g.tick(900);const before=g.get('stage').dataset.progress;g.get('black').events.click();await g.tick(1000);assert.equal(g.get('stage').dataset.breed,failBlack?'yellow':'black');assert.equal(g.get('stage').dataset.progress,before)}});
test('finish plays home animation, persists, and restart resets',async()=>{const g=await game();for(let i=0;i<12;i++){g.send('pointerdown');g.send('pointerup',446);await g.tick(820)}await g.tick(6000);assert.equal(g.get('stage').dataset.state,'complete');assert.equal(g.get('restart').hidden,false);g.get('restart').events.click();assert.equal(+g.get('stage').dataset.progress,0);assert.equal(g.get('stage').dataset.state,'idle')});
test('keyboard held arrows change tension and release commits',async()=>{const g=await game();const e={key:'ArrowLeft',preventDefault(){}};g.get('stage').events.keydown(e);await g.tick(700);assert.ok(+g.get('stage').dataset.preview>0);g.get('stage').events.keyup(e);await g.tick(900);assert.ok(+g.get('stage').dataset.progress>0)});
test('reduced motion completes through short ending',async()=>{const g=await game({reduced:true});for(let i=0;i<12;i++){g.send('pointerdown');g.send('pointerup',446);await g.tick(100)}await g.tick(1000);assert.equal(g.get('stage').dataset.state,'complete')});
